#!/usr/bin/env python

from __future__ import print_function

import rospy

def add_two_ints_client(x, y):
    pass



if __name__ == "__main__":
    rospy.init_node('move_uarm2_client')
    x = 1
    y = 2
    print("Requesting %s+%s" % (x, y))
    print("%s + %s = %s" % (x, y, add_two_ints_client(x, y)))